### ISSUE TITLE
 vpn not working

### ISSUE THREAD

**Issue by timmywong2003** [Everyday-VPN/Everyday-VPN#1]
I subscribe to this vpn in shadowrocket in ios13, but I can’t access the Internet after selecting the vpn. How to solve this problem?

**Comment by Everyday-VPN** [comment]
It is iran access only. + streisand app for ios is recommended
________________________________
From: timmywong2003 ***@***.***>
Sent: Friday, June 7, 2024 5:58 PM
To: Everyday-VPN/Everyday-VPN ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Everyday-VPN/Everyday-VPN] vpn not working (Issue #1)


I subscribe to this vpn in shadowrocket in ios13, but I can’t access the Internet after selecting the vpn. How to solve this problem?
